name: Fetch Crichd playlist

on:
  schedule:
    - cron: '*/30 * * * *' 
  workflow_dispatch:        

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch m3u content
        run: |
          curl -sL "${{ secrets.fatch_url }}" -o crichd.m3u

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add crichd.m3u
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Updated [$(TZ='Asia/Dhaka' date '+%Y-%m-%d %H:%M:%S')]"
            git push
          else
            echo "No changes detected."
          fi
