name: Crichd Auto Update
on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Unzip Protected Script
        run: unzip -P ${{ secrets.fatch_pass }} run.zip

      - name: Run Python Script
        run: python run.py

      - name: Delete Script After Run
        if: always()
        run: rm -f run.py

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cric.m3u
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update cric.m3u [$(TZ='Asia/Dhaka' date '+%Y-%m-%d %H:%M:%S')]"
            git push

permissions:
  contents: write
