name: Fetch Toffee

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  fetch-and-generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Download toffee_api.json (raw json)
        run: |
          curl -sL "${{ secrets.fatch_toffee }}" -o toffee_api.json

      - name: Generate M3U playlist
        run: |
          echo "#EXTM3U" > toffee_ott.m3u

          # Process the JSON file we downloaded earlier
          jq -c '.response[]' toffee_api.json | while read -r item; do
            name=$(echo "$item" | jq -r '.name')
            category=$(echo "$item" | jq -r '.category_name')
            logo=$(echo "$item" | jq -r '.logo')
            link=$(echo "$item" | jq -r '.link')
            cookie=$(echo "$item" | jq -r '.headers.cookie')
            user_agent=$(echo "$item" | jq -r '.headers."user-agent"')

            echo "#EXTINF:-1 group-title=\"$category\" tvg-id=\"\" tvg-logo=\"$logo\", $name" >> toffee_ott.m3u
            echo "#EXTVLCOPT:http-user-agent=$user_agent" >> toffee_ott.m3u
            echo "#EXTHTTP:{\"cookie\":\"$cookie\"}" >> toffee_ott.m3u
            echo "$link" >> toffee_ott.m3u
          done
          
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add toffee_api.json toffee_ott.m3u toffee_ns.m3u
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Updated [$(TZ='Asia/Dhaka' date '+%Y-%m-%d %H:%M:%S')]"
            git push
          else
            echo "No changes detected."
          fi
