name: Fetch Toffee

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  fetch-and-generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Download toffee_api.json (raw json)
        run: |
          curl -sL "${{ secrets.fatch_toffee }}" -o toffee_api.json

      - name: Generate M3U playlist
        run: |
          echo "#EXTM3U" > toffee_ott.m3u
          jq -r '.response[] | "#EXTINF:-1 group-title=\"\(.category_name)\" tvg-id=\"\" tvg-logo=\"\(.logo)\", \(.name)\n#EXTVLCOPT:http-user-agent=\"\(.headers."user-agent")\"\n#EXTHTTP:{\"cookie\":\"\(.headers.cookie)\"}\n\(.link)"' toffee_api.json >> toffee_ott.m3u
      - name: Generate JSON playlist
        run: |
          jq '[.response[] | {name: .name, logo: .logo, cookie: .headers.cookie, link: .link}]' toffee_api.json > toffee_ns.m3u
          
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add toffee_ott.m3u toffee_ns.m3u
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Updated [$(TZ='Asia/Dhaka' date '+%Y-%m-%d %H:%M:%S')]"
            git push
          else
            echo "No changes detected."
          fi
